/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 02a463fd924a410a3302e76821205a69)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	METRICS_SOURCE: "postgres";
	ANALYTICS_CACHE_TTL_MS: string;
	API_BASE_URL: string;
	DASHBOARD_FOUNDER_PASSWORD: string;
	DASHBOARD_FOUNDER_USERNAME: string;
	DASHBOARD_REVIEWER_PASSWORD: string;
	DASHBOARD_REVIEWER_USERNAME: string;
	DASHBOARD_SESSION_SECRET: string;
	MOCK_API: string;
	SUPABASE_URL: string;
	DATABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	ADMIN_EMAILS: string;
	GOOGLE_MONITORING_CREDENTIALS: string;
	GCP_PROJECT_ID: string;
	GCP_CLOUD_RUN_SERVICE: string;
	GCP_CLOUD_RUN_LOCATION: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "METRICS_SOURCE" | "ANALYTICS_CACHE_TTL_MS" | "API_BASE_URL" | "DASHBOARD_FOUNDER_PASSWORD" | "DASHBOARD_FOUNDER_USERNAME" | "DASHBOARD_REVIEWER_PASSWORD" | "DASHBOARD_REVIEWER_USERNAME" | "DASHBOARD_SESSION_SECRET" | "MOCK_API" | "SUPABASE_URL" | "DATABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "ADMIN_EMAILS" | "GOOGLE_MONITORING_CREDENTIALS" | "GCP_PROJECT_ID" | "GCP_CLOUD_RUN_SERVICE" | "GCP_CLOUD_RUN_LOCATION">> {}
}
